@startuml
box main process #LightBlue
actor main
participant BpCommunication
end box
participant "Android::Binder" as binder
box sub process
participant BnCommunication
participant MySensor
end box

main -> BpCommunication: getSignal(const uint16_t eventCode, \n std::function<void(int)> callback)
BpCommunication -> binder: writeInt32(eventCode)
@enduml